# Site settings
title: Jennifer Makes Things
email: hello@jennifermakesthings.com
url: "http://0.0.0.0:9999"
location: "Denver, Colorado"

# Jekyll
source:      ./app
destination: ./public_html

collections:
  # Site portfolio itms
  projects:
