# Site settings
title: Jennifer Falconburg
slogan: Graphic Designer
email: hello@jennifermakesthings.com
url: "http://0.0.0.0:9999"
location: "Denver, Colorado"

# Jekyll
source:      ./app
destination: ./public_html

collections:
  # Site portfolio itms
  projects:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: project--full
